### PR TITLE
Wrap ZMQ request in timeout

### LINKED ISSUE #123: When push-jobs-server is restarted, sometimes push-jobs-client send_string pending without timeout
# Description
When push-jobs-server is restarted, Sometime send_string(file : push-jobs-client / protocol_handler.rb, function : send_signed_message) pending without timeout.

# Push Jobs Client Version
2.1.4

# Platform Version
CentOS 7.2.1511

# Replication Case
step 1. Install push job server and push job client.
step 2. start push-jobs-server
step 3. start push-jobs-client
step 4. check node status (available)
step 5. restart push-jobs-server
        check node status (repeat step 5, sometimes the status does not change into available )

# Stacktrace
log 1. Push-Jobs-Client send heartbeat (sequence #7)
log 2. When push-jobs-server is restarted.
        incarnation ID changed
log 3. Push-Jobs-Client receive heartbeat (sequence #0),
        Server restart is detected,
        Reconfiguring after a randomly chosen 9.303089421512142 second delay to avoid storming the server.
log 4. Push-Jobs-Client try to send heartbeat (sequence #8)
        But socket is invalid, send_string pending without timeout
-------------------------------------------------------------------------------------------------------------------
/opt/push-jobs-client/embedded/lib/ruby/gems/2.1.0/gems/opscode-pushy-client-2.1.4/lib/pushy_client/protocol_handler.rb
def self.send_signed_message(socket, method, client_private_key, session_key, message)
      auth = case method
             when :rsa2048_sha1
               make_header_rsa(message, client_private_key)
             when :hmac_sha256
               make_header_hmac(message, session_key)
             end

      socket.send_string(auth, ZMQ::SNDMORE) ----> pending
      socket.send_string(message)

-------------------------------------------------------------------------------------------------------------------
log 5. trigger reconfigure Thread
log 6. Push-Jobs-Client receive heartbeat (sequence #1)
log 7. Push-Jobs-Client receive heartbeat (sequence #2)

===================================================================
log 1.
INFO: send_signed_json_command/@socket_lock.synchronize do #<Mutex:0x000000016f2650>
INFO: self.send_signed_message start
INFO: self.send_signed_message/send_string auth
INFO: self.send_signed_message/send_string message : {"node":"CEPH-OSD-R03-03_606","client":"CEPH-OSD-R03-03","protocol_version":"2.0","org":"trosadmin-org","type":"heartbeat","sequence":7,"timestamp":"Mon, 27 Feb 2017 08:06:48 GMT","incarnation_id":"b7306b52-d70f-4b55-af9c-6426fbd8199c","job_state":"idle","job_id":null}
INFO: self.send_signed_message end
INFO: send_signed_json_command/@socket_lock.synchronize do end

log 2. Push-jobs-server is restarted

log 3.
INFO: handle_message : is_command=false, header=Version:2.0;SigningMethod:rsa2048_sha1;Signature:pH0yymNlQaIij9l54PFuradc/JMn1oIbJ2wqSDMTXc69OoBBuV0JIMrNprATU6PXmfQhtFL/81Qyg7obuGNBAd0irZIYwtPLjLUtNcjC4/f8+bpUJcpAIYoy79dzt3FgSW/FLkWwpfusUq8HwPHc715Y+t1Qu0Ydtv86fVpzhv0kogL6KJ7nUg5qGFvIs0ckQAKtOunQwXQgtJzVLhK45BH5gZVRjzgTC73znpQ9XQKOZXR2W1mcfLpA09mWDGIm8jeYbDVJm7mjZ8RF/OTwoeZDZswbYK/ogg19bkCSeLu2h64j+fBnQdw4fSMUyf7W/iQmFwTgMOHQnCk/p9d8hA==, message={"sequence":0,"timestamp":"Mon, 27 Feb 2017 08:06:50 GMT","server":"ceph-mon-r03-01","type":"heartbeat","incarnation_id":"bd4ce5c5-ceaf-4fec-9e0e-7458667ba8fc"}
INFO: [CEPH-OSD-R03-03_606] Server restart detected (incarnation ID changed from 4571d2e5-39f2-4413-a9be-96130d6900b1 to bd4ce5c5-ceaf-4fec-9e0e-7458667ba8fc).  Reconfiguring after a randomly chosen 9.303089421512142 second delay to avoid storming the server ...

log 4.
INFO: heartbeat_thread/sleep 10.0
INFO: heartbeat_thread/client.send_heartbeat
INFO: send_command/protocol_handler.send_heartbeat
INFO: [CEPH-OSD-R03-03_606] Sending heartbeat (sequence #7)
INFO: send_signed_json_command/@socket_lock.synchronize do #<Mutex:0x000000016f2650>
INFO: self.send_signed_message start
INFO: self.send_signed_message/send_string auth -----------> send_string pending without timeout

log 5.
INFO: trigger_reconfigure/Thread.new start

log 6.
INFO: handle_message : is_command=false, header=Version:2.0;SigningMethod:rsa2048_sha1;Signature:vRXew7Lx/H9yfWYzHYGCG+tQ7tQTOEdKVZV7ZJkqOrqsZ8RhIYICrHM9vhAdbZ6MnvFSlNxgSpBzN67E+/tU+SUMlE2qLoPXS8PYaZMsJqG64uNrX2S7vyJWEPZgiFOMQ+BdVVnZ22KH40qCzgSCXP2jP2lLjz6KSEh4VR3UKq56aADb5UoR2DrYzGEkU+ndYDTNRtxeCv2a8VB2ZGP96MOHIfJm/wq3mdqatP3hCM6M0WWbfZe2AMc536KrdSW+ycqiX42dRX721+QQEEDiqJi6+852I3iEPB575WCaEfxHP6hXIK0Twj0APAe3J2Lg4QwmIIkfu6T7VwZZRig/0Q==, message={"sequence":1,"timestamp":"Mon, 27 Feb 2017 08:07:00 GMT","server":"ceph-mon-r03-01","type":"heartbeat","incarnation_id":"bd4ce5c5-ceaf-4fec-9e0e-7458667ba8fc"}

log 7.
INFO: handle_message : is_command=false, header=Version:2.0;SigningMethod:rsa2048_sha1;Signature:dwv2dTO39DVc7fKOIRaNAaPkGOQ8e5YdKoqyBPsy5uGqJ6GrfC9fnp6CaUz4bu4x1c0c4vMb2Kev0BV/NMnfCMFi0LXF7fHKBm0XJ1DKtK2ih+MZWN79sfFeQ4ho0nYxSonmi8I5SNRzx1kVxlAm2MRfigKlB87kPaPEBcGQvWCtQtyCZlwHc5CTIj9mzlf121PkgC4dfm4V/YtKKNFK5s0Wdsf1gDWv0T6D4JNsytZVkbqKsWf0HAibHHHU5JBDmea2GGM7TgrdGApy7uy6MSMaQYnwUHGZbagoP1WXIPqfB61ohj49lgL5lc/7Oaq7Gxmec+HbfcXZQBdLCvTMTg==, message={"sequence":2,"timestamp":"Mon, 27 Feb 2017 08:07:10 GMT","server":"ceph-mon-r03-01","type":"heartbeat","incarnation_id":"bd4ce5c5-ceaf-4fec-9e0e-7458667ba8fc"}

# Fix It

vi /opt/push-jobs-client/embedded/lib/ruby/gems/2.1.0/gems/opscode-pushy-client-2.1.4/lib/pushy_client/protocol_handler.rb

require 'timeout' 

def self.send_signed_message(socket, method, client_private_key, session_key, message)
      auth = case method
             when :rsa2048_sha1
               make_header_rsa(message, client_private_key)
             when :hmac_sha256
               make_header_hmac(message, session_key)
             end

      # add timeout
      begin
          timeout(30) do
              socket.send_string(auth, ZMQ::SNDMORE)
              socket.send_string(message)
          end
      rescue Timeout::Error
          Chef::Log.info("Error : Timed out!")
      end
    end
end

### PR DESCRIPTION
**Pull request by nsdavidson**
Signed-off-by: Nolan Davidson <ndavidson@chef.io>

### Description

As noted in #123, the push jobs client will sometimes hang on the
send_string call when the push jobs server is restarted (or is replaced
by another PJ server).  After adding this timeout, I have been able to
successfully restart and replace the PJ server without the client
hanging consistently.

### Issues Resolved

#123 

### Check List

- [ ] New functionality includes tests
- [ ] All tests pass
- [ ] CHANGELOG.md has been updated
- [ ] All commits have been signed-off for the Developer Certificate of Origin. See <https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco>

### CODE REVIEW

**Comment by irvingpop** [comment]
howdy @nsdavidson could you please push an ad-hoc build through CI and place it somewhere externally consumable to enable testing?

**Comment by nsdavidson** [comment]
If anyone is interested in testing this out, a RHEL 6 pushy-client build can be found here: https://s3-us-west-2.amazonaws.com/sce-pub/push-jobs-client-2.4.1%2B20170912123217-1.el6.x86_64.rpm

I can share other platform builds if needed as well.

File: lib/pushy_client/protocol_handler.rb [hunk 1]
```diff
@@ -483,8 +483,14 @@ def self.send_signed_message(socket, method, client_private_key, session_key, me
...
                make_header_hmac(message, session_key)
              end
-      socket.send_string(auth, ZMQ::SNDMORE)
-      socket.send_string(message)
+      begin
+        timeout(10) do
+          socket.send_string(auth, ZMQ::SNDMORE)
+          socket.send_string(message)
+        end
+      rescue
```
Comment (btm) [inline lib/pushy_client/protocol_handler.rb]: Please rescue just `Timeout::Error` here. Since we aren't printing the exception in the message below, it is possible that some other exception would be getting raise and it would be blindly rescued here with an incorrect message about what happened.

File: lib/pushy_client/protocol_handler.rb [hunk 2]
```diff
@@ -483,8 +483,14 @@ def self.send_signed_message(socket, method, client_private_key, session_key, me
              when :hmac_sha256
                make_header_hmac(message, session_key)
              end
-      socket.send_string(auth, ZMQ::SNDMORE)
-      socket.send_string(message)
+      begin
+        timeout(10) do
```
Comment (btm) [inline lib/pushy_client/protocol_handler.rb]:
```
/opt/push-jobs-client/embedded/lib/ruby/gems/2.4.0/gems/opscode-pushy-client-2.3.5/lib/pushy_client/protocol_handler.rb:487:in `send_signed_message': Object#timeout is deprecated, use Timeout.timeout instead.
```

**Comment by btm** [comment]
Thanks for digging into this! Unfortunately it looks like we have minimal unit tests already, so we can forgo adding those for this fix. A couple comments to look at and then this will be good.

File: lib/pushy_client/protocol_handler.rb (hunk 2 above)
Comment (btm) [reply lib/pushy_client/protocol_handler.rb]: In case someone doesn't scroll right on that error, this should be `Timeout.timeout` instead of `timeout`.

**Comment by jittipa** [comment]
Installed the rpm for this new push-jobs client on two nodes running RHEL6. When the push-jobs server was just restarted - chef-server-ctl restart opscode-pushy-server, both nodes checked back in properly, i.e., knife node status showed both nodes as available. Unfortunately, if I kept the server down for a certain period of time and restarted, one of the two nodes did not.

**Comment by nsdavidson** [comment]
Thanks for the feedback @btm!  Requested changes made.  

@jittipa Hrmm...this fix is specifically for the case of the server being unavailable for more than a few seconds.  Would it be possible for you to grab the push-client logs off the node that's not recovering?

**Comment by jittipa** [comment]
@nsdavidson After almost 1 hour (15:21:51 - 16:17:30), the client finally checked back in and is now available.

2017-09-13_16:17:30.15059 INFO: [jobsserver] Config is now 3586.204102130747 seconds old.  Reconfiguring / reloading keys ...

**Comment by lcc2207** [comment]
@nsdavidson can you publish an RHEL 7 version or Amazon linux version?

**Comment by nsdavidson** [comment]
@lcc2207 sure thing: https://s3-us-west-2.amazonaws.com/sce-pub/push-jobs-client-2.4.1%2B20170912123217-1.el7.x86_64.rpm

**Comment by irvingpop** [comment]
Amazon Linux is usually good with the RHEL6 packages

**Comment by btm** [comment]
And what to do with the message? Retry after a restart? I had looked at something like this earlier as a pattern but got distracted.

http://zguide.zeromq.org/rb:lpclient

**Comment by nsdavidson** [comment]
@btm @markan I rolled in Mark's changes from PR #144 with some tweaks.

In addition to scheduling a reconfigure when the ZMQ socket times out, I also added that logic to a failed config download.  I noticed that if we try to download a config, and it fails after the standard 5 retries, the client would get into that wedged state waiting for it's next 3600 second reconfigure.  

I tested this change and it is handling both short periods of the push-job server being offline and a complete server teardown/rebuild consistently.

**Comment by irvingpop** [comment]
:shipit: !
